### ISSUE TITLE
where is "ms1m-retinaface-t1-clean.txt" file

### ISSUE THREAD

**Issue by Samonsix** [cavalleria/cavaface.pytorch#11]
I download train dateset as "For training data, please download the ms1m-retinaface in https://github.com/deepinsight/insightface/tree/master/iccv19-challenge."
but not found ms1m-retinaface-t1-clean.txt, i got this files: 
-rw-r--r-- 1 shengyang root  73M Apr  9  2019 agedb_30.bin
-rw-r--r-- 1 shengyang root  73M Apr  1  2019 cfp_fp.bin
-rw-r--r-- 1 shengyang root  63M Apr  1  2019 lfw.bin
-rw-r--r-- 1 shengyang root   14 Apr  1  2019 property
-rw-r--r-- 1 shengyang root  98M Apr  1  2019 train.idx
-rw-r--r-- 1 shengyang root 412M Apr  1  2019 train.lst
-rw-r--r-- 1 shengyang root  28G Apr  1  2019 train.rec

how to make train dataset? thank you!

**Comment by cavalleria** [comment]
please generate img list file by yourself.

**Comment by pawan9** [comment]
i also have the same question, i downloaded the dataset and extracted images from the .rec file using the the code in `prepare_data.py` from face.evoLVe.PyTorch repo.

@cavalleria can you please tell what the contents of this file would look like.

**Comment by cavalleria** [comment]
yes

**Comment by ReverseSystem001** [comment]
Do you know how to make the ms1m-retinaface-t1-clean.txt now?

**Comment by ReverseSystem001** [comment]
> i also have the same question, i downloaded the dataset and extracted images from the .rec file using the the code in `prepare_data.py` from face.evoLVe.PyTorch repo.
> 
> @cavalleria can you please tell what the contents of this file would look like. would it be something like
> 
> ```
> 0/1.jpg 0
> 0/2.jpg 0
> 1/1.jpg 1
> 1/2.jpg 1
> ```
> 
> since after extraction i get folders with numeric names each containing images belonging to a single person
> 
> ![ms1m_extracted](https://user-images.githubusercontent.com/3811164/86081009-dee8d500-bab1-11ea-9de5-d317f9177b51.PNG)

Do you know how to make the ms1m-retinaface-t1-clean.txt now?

**Comment by ReverseSystem001** [comment]
> found ms1m-retinaface-t1-clean.txt

how do you train without ms1m-retinaface-t1-clean.txt or how do you make the ms1m-retinaface-t1-clean.txt.
hope your replay

**Comment by cavalleria** [comment]
please make ms1m-retinaface-t1-clean.txt by yourself. The format is` image_path \t id`
