### ISSUE TITLE
ReXnet based results

### ISSUE THREAD

**Issue by DietDietDiet** [cavalleria/cavaface.pytorch#22]
Hi, big thanks for your great work, 6666!
Have you tried rexnet based models? If yes, could u share the results? Thanks!

**Comment by cavalleria** [comment]
Yes. I have trained rexnetv1, result is below
<pre>Params:  3.66 M
Flops: 0.8 GFLOPS 
LFW Acc: 0.99749, CFP_FP Acc: 0.96785, AgeDB Acc: 0.97783, VGG2_FP Acc: 0.94119</pre>
the megaface and  ijbc evaluation have some bugs.

**Comment by DietDietDiet** [comment]
感谢~ 期待rexnet和蒸馏的更新
