### ISSUE TITLE
GPU problems

### ISSUE THREAD

**Issue by ReverseSystem001** [cavalleria/cavaface.pytorch#23]
I have 4 GPUS. when I write GPU=[0,1,2,3] in the config.py, it will report errors. But when i write GPU=[0,1]. it works well. That's strange

**Comment by cavalleria** [comment]
Do you set gpu avaiable env `CUDA_VISIBLE_DEVICES`?

**Comment by ReverseSystem001** [comment]
you mean I should run sh train.sh like:  CUDA_VISIBLE_DEVICES=0,1,2,3 sh train.sh ?

**Comment by cavalleria** [comment]
yes, set CUDA_VISIBLE_DEVICES="0,1,2,3"

**Comment by cavalleria** [comment]
yes, set `CUDA_VISIBLE_DEVICES="0,1,2,3"`

**Comment by ReverseSystem001** [comment]
It  seems does not work.
![1](https://user-images.githubusercontent.com/23073337/86769166-4dfd9500-c081-11ea-80ff-5c82ea0a923f.png)

**Comment by cavalleria** [comment]
Can you provide your training commod?

**Comment by ReverseSystem001** [comment]
pick any two from the gpus, it will works. when the gpu numbers are 3 or 4 .it will report errors like above.   all of the config are default.  I run :  CUDA_VISIBLE_DEVICES=0,1,2,3 sh train.sh, training commod?? you mean which script？

**Comment by cavalleria** [comment]
please change `CUDA_VISIBLE_DEVICES="0,1,2,3"` in train.sh , then run command `sh train.sh`

**Comment by ReverseSystem001** [comment]
get it. thanks
