### ISSUE TITLE
some problem about citrus_base_infer.py

### ISSUE THREAD

**Issue by ReverseSystem001** [cavalleria/cavaface.pytorch#25]
when i read the function run()(line 94) in class readThread (threading.Thread)(line 85) of citrus_base_infer.py. I doubt why there is no normalization before sending the img to the network structure: As far as I know, there is such an operation in training
   def run(self):
        global signal_stop
        unfinished = True
        while not signal_stop and unfinished:
            try:
                image_path, outpath = self.in_q.get(timeout=1)
                out_img = []
                img = self.read_func(image_path, self.shape[0]==1)
                if len(img.shape) == 3:
                    img = img[:,:,::-1] #to rgb
                    img = np.transpose( img, (2,0,1) )
                else:
                    img = img[np.newaxis,:]
                attempts = [0,1] if self.is_flip else [0]
Hope your replay. Thx

**Comment by cavalleria** [comment]
please refer forward function in utils/pytorch_tool.py

**Comment by ReverseSystem001** [comment]
> please refer forward function in utils/pytorch_tool.py

sorry. I did not notice it. Thx
