### ISSUE TITLE
about the results reported on model zoo

### ISSUE THREAD

**Issue by ainnn** [cavalleria/cavaface.pytorch#35]
thanks for sharing such a great work! here i have some questions about the results and training details:
1. are all the models' training data the same? is it ms1m-retina? if not, have you removed duplicates from megaface?
2. i have made effort to achieve 99%+ on megaface, but only get 98.5% for now (training data is ms1m-retina). I wonder if it's quite easy to achieve 99% if using you scripts with default settings? have you used horizontal flipped image's feature when test on megaface? what are the training batch size and end epoch?
3. do all the listed IR-SE-100 models train from scratch? or finetune on one model? if so, which?

looking forward to your reply. thank you.

**Comment by cavalleria** [comment]
1.The training data is ms1m-retina, but we slightly clean it. The megaface is from insightface.
2.Batch size is 128*8=1024，epoch=24, horizontal flip is used.
3.all models train from scratch.

**Comment by ainnn** [comment]
got it. thanks!
