### ISSUE TITLE
RGB Image or Gray Scale Image

### ISSUE THREAD

**Issue by FeiMiBa** [cavalleria/cavaface.pytorch#40]
Thanks for your great work!

Did you train/test all these on RGB images? I have a task to train/test on gray scale images, do you think i will suffer from performance degradation in case I train from scratch with all your default settings? Any suggestions? Thank you!

**Comment by cavalleria** [comment]
Yes, all images are rgb. I think the performance will degrade if you train with gray image.

**Comment by xsacha** [comment]
Probably change the input channels to 1 so you at least get a performance improvement in using grayscale, if that is your requirement.

**Comment by FeiMiBa** [comment]
Have you cleaned the ms1m-retinaface dataset, or you just used it anywhere?

**Comment by FeiMiBa** [comment]
> Yes, all images are rgb. I think the performance will degrade if you train with gray image.

Have you cleaned the ms1m-retinaface dataset, or you just used it anyway?

**Comment by cavalleria** [comment]
> > Yes, all images are rgb. I think the performance will degrade if you train with gray image.
> 
> Have you cleaned the ms1m-retinaface dataset, or you just used it anyway?

yes. slightly cleaned

**Comment by FeiMiBa** [comment]
> > > Yes, all images are rgb. I think the performance will degrade if you train with gray image.
> > 
> > 
> > Have you cleaned the ms1m-retinaface dataset, or you just used it anyway?
> 
> yes. slightly cleaned

Awesome, thank you!
