### ISSUE TITLE
About MegaFace testing

### ISSUE THREAD

**Issue by XWalways** [cavalleria/cavaface.pytorch#41]
when running
`r = requests.post("http://127.0.0.1:%d/eval"%(eval_info["args"].port), data=eval_info).json()`
Response [404], so .json() returns

simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

how to solve this?

**Comment by Monkey2003** [comment]
Did you figure out how to solve this problem? Please inform me if you did.

**Comment by XWalways** [comment]
> Did you figure out how to solve this problem? Please inform me if you did.

you should run `python evaluate_service.py` firstly, then run `sh run.sh` in another terminal window
