### ISSUE TITLE
About CircleLoss

### ISSUE THREAD

**Issue by bobo0810** [cavalleria/cavaface.pytorch#45]
@cavalleria Hello, I have observed that there is ‘Circle-Loss’ in the introduction, but not in the code. Is it because of poor performance?Thanks!

**Comment by cavalleria** [comment]
circle loss is implemented in metrics.py.

**Comment by bobo0810** [comment]
> circle loss is implemented in metrics.py.

Thanks for your work. Maybe you need to update the readme.md
