### ISSUE TITLE
How to load the pretrained model?

### ISSUE THREAD

**Issue by johnnysclai** [cavalleria/cavaface.pytorch#57]
I downloaded the checkpoint from MODEL_ZOO but it fails to load the model. 
I load the checkpoint as follows, but it shows the error: ``ModuleNotFoundError: No module named '__torch__'``

```python
BACKBONE.load_state_dict(torch.load('IR_SE_100_Combined_Epoch_24.pth'))
```

**Comment by cavalleria** [comment]
the model in model_zoo is saved by torch.jit.save, you can load use torch.jit.load？

**Comment by johnnysclai** [comment]
I see. Solved thank you.
