### ISSUE TITLE
eval is not in parallel while traning

### ISSUE THREAD

**Issue by lsmale** [cavalleria/cavaface.pytorch#59]

**Comment by lsmale** [comment]
Hi, thx for this great work! 
I found when evaluating on the training stage, the evaluating is not gpu parallel, and is very slow compare to training time, have you have any idea of how to fix it?

**Comment by cavalleria** [comment]
the eval code has some redundant operation, i will improve it later.

**Comment by cavalleria** [comment]
val set evaluation speed has been fast
