### ISSUE TITLE
模型加载问题。

### ISSUE THREAD

**Issue by xw0629** [cavalleria/cavaface.pytorch#67]
试了torch.load和torch.jit.load，都不行，参数是在model zoo里面下载的，两个100的模型。

**Comment by cavalleria** [comment]
我用的没问题的，报啥错啊

**Comment by xw0629** [comment]
用torch.load会报No module named '__torch__'，看了有个issue你说用torch.jit.load，model.load_state_dict(torch.jit.load(weight))，然后报AttributeError: 'RecursiveScriptModule' object has no attribute 'keys'，torch的版本也换成1.4，还是这个错

**Comment by xw0629** [comment]
`import torch
from cava_irse import IR_100

weight = "../../../epoch_16_7.pth"
model = IR_100([112,112])
model.load_state_dict(torch.jit.load(weight))`

**Comment by xw0629** [comment]
`
import torch
from cava_irse import IR_100

weight = "../../../epoch_16_7.pth"
model = IR_100([112,112])
model.load_state_dict(torch.jit.load(weight))
`

**Comment by cavalleria** [comment]
先确保你的环境没问题
model=torch.jit.load(model_path, map_location=ctx)

**Comment by xw0629** [comment]
ok可以了，thanks。

**Comment by zhiplain** [comment]
> ok可以了，thanks。

您好请问是怎么解决的，我的还有这个问题，不知怎么操作啊

**Comment by zhiplain** [comment]
如果是自己训练的化，加载自己的模型没有问题，但是如果使用mode zoo中的模型，就会出现AttributeError: 'RecursiveScriptModule' object has no attribute 'keys'的问题

**Comment by cavalleria** [comment]
我使用jit保存的模型，如果load model zoo的模型要用上面torch.jit.load
