### ISSUE TITLE
How to Train Custom Data

### ISSUE THREAD

**Issue by nobody-cheng** [cavalleria/cavaface.pytorch#76]
How to Train Custom Data

**Comment by cavalleria** [comment]
pack your custom data into mxnet `.rec` file. you can refer insightface repo.

**Comment by nobody-cheng** [comment]
> pack your custom data into mxnet `.rec` file. you can refer insightface repo.
谢谢，请问自己的测试集如何制作，参考哪里
下载的lfw是做成.blp格式

**Comment by cavalleria** [comment]
测试集在face.evoLVe.PyTorch中下载lfw,agedb_30,cfp_fp等就好了

**Comment by nobody-cheng** [comment]
> 测试集在face.evoLVe.PyTorch中下载lfw,agedb_30,cfp_fp等就好了
多谢，lfw,agedb_30我已经下了，
其实我是想把自己的人脸数据集做成 face.evoLVe.PyTorch中lfw格式的形式，我不知道该参考哪些来整理自己的测试集，数据集的_***.blp

**Comment by cavalleria** [comment]
1.用bcolz制作
2.可以直接制作成.bin，然后在代码中改下读取bin就好了
